[stack]
id = "io.buildpacks.stacks.bionic"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.5.0"

[[buildpacks]]
  id = "heroku/maven"
  # TODO: release with https://github.com/heroku/heroku-buildpack-java/pull/128
  uri = "https://github.com/heroku/heroku-buildpack-java/releases/download/cnb/heroku-buildpack-maven.tgz"

[[buildpacks]]
  id = "heroku/jvm"
  # TODO: release with https://github.com/heroku/heroku-buildpack-jvm-common/pull/118
  uri = "https://github.com/heroku/heroku-buildpack-jvm-common/releases/download/cnb/heroku-buildpack-jvm-common.tgz"

[[buildpacks]]
  id = "heroku/ruby"
  # TODO: release with https://github.com/heroku/heroku-buildpack-ruby/pull/945
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/cnb-alpha/ruby-buildpack-vCNB-alpha.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "https://github.com/heroku/procfile-cnb/releases/download/v0.4/procfile-cnb-v0.4.tgz"

[[buildpacks]]
  id = "heroku/python"
  uri = "buildpacks/python"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "buildpacks/gradle"

[[buildpacks]]
  id = "heroku/php"
  uri = "buildpacks/php"

[[buildpacks]]
  id = "heroku/go"
  uri = "buildpacks/go"

[[buildpacks]]
  id = "heroku/nodejs-engine"
  # TODO: release with https://github.com/heroku/nodejs-engine-buildpack/pull/31
  uri = "/Users/jesse.brown/dev/nodejs-engine-buildpack/nodejs-engine-buildpack-v0.4.2.tgz"

[[buildpacks]]
  id = "heroku/nodejs-npm"
  # TODO: release with https://github.com/heroku/nodejs-npm-buildpack/pull/18
  uri = "/Users/jesse.brown/dev/nodejs-npm-buildpack/nodejs-npm-buildpack-v0.1.3.tgz"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.4"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.0.5.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.4"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/jvm"
    version = "0.1"

  [[order.group]]
    id = "heroku/maven"
    version = "0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.4"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/gradle"
    version = "0.0.5.2"

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.0.5.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.4"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.0.5.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.4"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.4.2"

  [[order.group]]
    id = "heroku/nodejs-npm"
    version = "0.1.3"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.4"
    optional = true
