[stack]
id = "heroku-20"
build-image = "heroku/pack:20-build"
run-image = "heroku/pack:20"

[lifecycle]
version = "0.10.1"

[[buildpacks]]
  id = "heroku/maven"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-maven-buildpack@sha256:7bff54457286a9a36dbcaec77ab041d61c2e1a47741d459c3457e429f6d2f268"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-jvm-buildpack@sha256:37483599729c5afbd747a2c8d5965347a32d134e4c5d1b9b5dadfffa81fe5014"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-java-buildpack@sha256:7032d52f0612152e180503a1c8c30ab1f8155345d0035889af66adac79b6c633"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-gradle-buildpack@sha256:7163f393470de8255fe03e06d55d3ae7bf59bf683f4ff2651ed92b6538eed0ad"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-scala-buildpack@sha256:7a58fd9774925a6e23ce638cc4c7b57fdb9a14092632bc00c10081bb226f19b3"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-java-function-buildpack@sha256:42dfacaba0426856412c4c0ac68516ddfb58f3fbaa4ba00b79e6d5ca0cbe26a1"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/v222/heroku-buildpack-ruby-v222.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:0.6.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3.1&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "heroku/nodejs-engine"
  uri = "https://github.com/heroku/nodejs-engine-buildpack/releases/download/v0.7.0/nodejs-engine-buildpack-v0.7.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-npm"
  uri = "https://github.com/heroku/nodejs-npm-buildpack/releases/download/v0.4.0/nodejs-npm-buildpack-v0.4.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-yarn"
  uri = "https://github.com/heroku/nodejs-yarn-buildpack/releases/download/v0.1.0/nodejs-yarn-buildpack-v0.1.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-typescript"
  uri = "https://github.com/heroku/nodejs-typescript-buildpack/releases/download/v0.2.0/nodejs-typescript-buildpack-v0.2.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/heroku_nodejs"

[[buildpacks]]
  id = "salesforce/nodejs-fn"
  uri = "https://github.com/forcedotcom/nodejs-sf-fx-buildpack/releases/download/v2.0.5/nodejs-sf-fx-buildpack-v2.0.5.tgz"

[[buildpacks]]
  id = "projectriff/streaming-http-adapter"
  uri = "docker://gcr.io/projectriff/streaming-http-adapter:1.4.0"

[[buildpacks]]
  id = "projectriff/node-function"
  uri = "docker://gcr.io/projectriff/node-function:1.5.0"

[[buildpacks]]
  id = "evergreen/fn"
  uri = "buildpacks/evergreen_fn"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.88"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.1"
    optional = true

[[order]]
  [[order.group]]
    id = "evergreen/fn"
    version = "0.3.0"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.2.0"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.3.1"
