[[buildpacks]]
  id = "heroku/java"
  uri = "https://github.com/heroku/java-buildpack/releases/download/v0.3/java-buildpack-v0.3.tgz"

[[groups]]
  [[groups.buildpacks]]
    id = "heroku/java"
    version = "0.3"
