[[buildpacks]]
  id = "heroku/java"
  uri = "https://github.com/heroku/java-buildpack/releases/download/v0.8/java-buildpack-v0.8.tgz"

[[groups]]
  [[groups.buildpacks]]
    id = "heroku/java"
    version = "0.8"
