[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.6.1"

[[buildpacks]]
  id = "heroku/maven"
  uri = "https://github.com/heroku/heroku-buildpack-java/releases/download/cnb/heroku-buildpack-maven.tgz"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "https://github.com/heroku/heroku-buildpack-jvm-common/releases/download/v96/heroku-jvm-cnb.tgz"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/cnb-alpha/ruby-buildpack-vCNB-alpha.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "https://github.com/heroku/procfile-cnb/releases/download/v0.5/procfile-cnb-v0.5.tgz"

[[buildpacks]]
  id = "heroku/python"
  uri = "buildpacks/python"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "buildpacks/gradle"

[[buildpacks]]
  id = "heroku/scala"
  uri = "buildpacks/scala"

[[buildpacks]]
  id = "heroku/php"
  uri = "buildpacks/php"

[[buildpacks]]
  id = "heroku/go"
  uri = "buildpacks/go"

[[buildpacks]]
  id = "heroku/nodejs-engine"
  uri = "https://github.com/heroku/nodejs-engine-buildpack/releases/download/v0.4.3/nodejs-engine-buildpack-v0.4.3.tgz"

[[buildpacks]]
  id = "heroku/nodejs-npm"
  uri = "https://github.com/heroku/nodejs-npm-buildpack/releases/download/v0.1.4/nodejs-npm-buildpack-v0.1.4.tgz"

[[buildpacks]]
  id = "heroku/nodejs-yarn"
  uri = "https://github.com/heroku/nodejs-yarn-buildpack/releases/download/v0.0.1/nodejs-yarn-buildpack-v0.0.1.tgz"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/jvm"
    version = "0.1"

  [[order.group]]
    id = "heroku/maven"
    version = "0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/gradle"
    version = "0.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.1.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.4.3"

  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "0.0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.4.3"

  [[order.group]]
    id = "heroku/nodejs-npm"
    version = "0.1.4"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.5"
    optional = true
