[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/nodejs"
  latest = true

[[buildpacks]]
  id = "heroku/node-function"
  uri = "https://github.com/heroku/node-function-buildpack/releases/download/v0.4.0/node-function-buildpack-v0.4.0.tgz"

[[groups]]
  # node functions
  buildpacks = [
    { id = "heroku/nodejs", version = "latest" },
    { id = "heroku/node-function", version = "0.4.0" },
  ]
